# Use postgres/example user/password credentials
version: '3.4'

services:

  db:
    image: postgis/postgis
    restart: always
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      FORCE_SSL: "false"
      POSTGRES_DB: gis
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    volumes:
      - ./dbdata:/var/lib/postgresql:rw
    ports:
    - published: 45432
      target: 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080